data "azurerm_client_config" "current" {}

# ---------------------------------------------------------------------------
# Azure AD Application for GitHub Actions
# ---------------------------------------------------------------------------
resource "azuread_application" "github_actions" {
  display_name = "sp-github-actions-${var.project}-${var.environment}"
  owners       = [data.azurerm_client_config.current.object_id]
}

resource "azuread_service_principal" "github_actions" {
  client_id                    = azuread_application.github_actions.client_id
  app_role_assignment_required = false
  owners                       = [data.azurerm_client_config.current.object_id]
}

# ---------------------------------------------------------------------------
# Federated Identity Credentials (OIDC — no client secret needed)
# ---------------------------------------------------------------------------
resource "azuread_application_federated_identity_credential" "main_branch" {
  application_id = azuread_application.github_actions.id
  display_name   = "github-oidc-main-${var.project}-${var.environment}"
  description    = "GitHub Actions OIDC for main branch deployments"
  audiences      = ["api://AzureADTokenExchange"]
  issuer         = "https://token.actions.githubusercontent.com"
  subject        = "repo:${var.github_org}/${var.github_repo_name}:ref:refs/heads/main"
}

resource "azuread_application_federated_identity_credential" "pull_request" {
  application_id = azuread_application.github_actions.id
  display_name   = "github-oidc-pr-${var.project}-${var.environment}"
  description    = "GitHub Actions OIDC for pull request workflows"
  audiences      = ["api://AzureADTokenExchange"]
  issuer         = "https://token.actions.githubusercontent.com"
  subject        = "repo:${var.github_org}/${var.github_repo_name}:pull_request"
}

resource "azuread_application_federated_identity_credential" "prod_environment" {
  application_id = azuread_application.github_actions.id
  display_name   = "github-oidc-env-prod-${var.project}-${var.environment}"
  description    = "GitHub Actions OIDC for production environment deployments"
  audiences      = ["api://AzureADTokenExchange"]
  issuer         = "https://token.actions.githubusercontent.com"
  subject        = "repo:${var.github_org}/${var.github_repo_name}:environment:production"
}

# ---------------------------------------------------------------------------
# RBAC — ACR Push for GitHub Actions SP
# ---------------------------------------------------------------------------
resource "azurerm_role_assignment" "acr_push" {
  scope                = var.acr_id
  role_definition_name = "AcrPush"
  principal_id         = azuread_service_principal.github_actions.object_id
}

# ---------------------------------------------------------------------------
# RBAC — Contributor on Resource Group (for ACA deployments)
# ---------------------------------------------------------------------------
resource "azurerm_role_assignment" "rg_contributor" {
  scope                = "/subscriptions/${var.subscription_id}/resourceGroups/${var.resource_group_name}"
  role_definition_name = "Contributor"
  principal_id         = azuread_service_principal.github_actions.object_id
}

# ---------------------------------------------------------------------------
# RBAC — Key Vault Secrets Reader for CI/CD (to read deploy-time secrets)
# ---------------------------------------------------------------------------
resource "azurerm_role_assignment" "kv_reader" {
  scope                = var.key_vault_id
  role_definition_name = "Key Vault Secrets User"
  principal_id         = azuread_service_principal.github_actions.object_id
}

# ---------------------------------------------------------------------------
# GitHub Actions Workflow
#
# Security hardening applied:
#   - All third-party action uses: pinned to immutable full commit SHAs
#   - Trivy vulnerability scan fails the build on HIGH/CRITICAL findings
#     (|| true removed); add --exit-code 0 temporarily if a soft-fail
#     transitional period is needed and remove before GA
#   - Image tags use git SHA (immutable), not :latest
#   - Workflow file written relative to path.root (not ../../ traversal)
# ---------------------------------------------------------------------------
resource "local_file" "github_workflow" {
  filename        = "${path.root}/.github/workflows/deploy.yml"
  file_permission = "0644"
  content         = <<-YAML
    # =========================================================
    # eShopOnWeb — CI/CD Pipeline
    # Generated by Terraform — commit to source control.
    # DO NOT EDIT MANUALLY; regenerate via terraform apply.
    # =========================================================
    name: Build and Deploy eShopOnWeb

    on:
      push:
        branches: [main]
      pull_request:
        branches: [main]
      workflow_dispatch:

    permissions:
      id-token: write
      contents: read
      packages: write
      security-events: write   # for uploading SARIF scan results

    env:
      REGISTRY: $${ACR_LOGIN_SERVER}
      WEB_IMAGE_NAME: eshop/web
      API_IMAGE_NAME: eshop/publicapi

    jobs:
      # -------------------------------------------------------
      # Job 1: Build & Test
      # -------------------------------------------------------
      build-and-test:
        name: Build and Test
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            # actions/checkout — pinned SHA (v4.1.7)
            uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

          - name: Setup .NET 8
            # actions/setup-dotnet — pinned SHA (v4.0.0)
            uses: actions/setup-dotnet@4d6c8fcf3c8f7a60068d26b594648e99df24cee3
            with:
              dotnet-version: '8.0.x'

          - name: Restore dependencies
            run: dotnet restore eShopOnWeb.sln

          - name: Build solution
            run: dotnet build eShopOnWeb.sln --no-restore --configuration Release

          - name: Run unit tests
            run: dotnet test tests/UnitTests/UnitTests.csproj --no-build --configuration Release --logger trx --results-directory ./test-results

          - name: Run integration tests
            run: dotnet test tests/IntegrationTests/IntegrationTests.csproj --no-build --configuration Release --logger trx --results-directory ./test-results

          - name: Run functional tests
            run: dotnet test tests/FunctionalTests/FunctionalTests.csproj --no-build --configuration Release --logger trx --results-directory ./test-results

          - name: Publish test results
            # dorny/test-reporter — pinned SHA (v1.9.1)
            uses: dorny/test-reporter@31a54ee0be72d238d8c39ec9b6eac0d3ae7b7d2d
            if: always()
            with:
              name: .NET Tests
              path: ./test-results/*.trx
              reporter: dotnet-trx

      # -------------------------------------------------------
      # Job 2: Build, Scan & Push Docker Images
      # -------------------------------------------------------
      build-and-push:
        name: Build, Scan and Push Images
        runs-on: ubuntu-latest
        needs: build-and-test
        if: github.event_name != 'pull_request'
        outputs:
          image-tag: ${{ steps.meta.outputs.version }}

        steps:
          - name: Checkout repository
            uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

          - name: Azure Login (OIDC)
            # azure/login — pinned SHA (v2.1.1)
            uses: azure/login@6c251865b4e6290e7b78be643ea2d005bc51f69a
            with:
              client-id: ${{ secrets.AZURE_CLIENT_ID }}
              tenant-id: ${{ secrets.AZURE_TENANT_ID }}
              subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

          - name: Login to ACR
            run: az acr login --name ${{ secrets.ACR_NAME }}

          - name: Set image tag (immutable git SHA)
            id: meta
            run: echo "version=${{ github.sha }}" >> $GITHUB_OUTPUT

          - name: Build Web image
            run: |
              docker build \
                -f src/Web/Dockerfile \
                -t ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.WEB_IMAGE_NAME }}:${{ steps.meta.outputs.version }} \
                .

          - name: Scan Web image for vulnerabilities
            # aquasecurity/trivy-action — pinned SHA (v0.24.0)
            uses: aquasecurity/trivy-action@6e7b7d1fd3e4fef0c5fa8cce1229c54b2c9bd0d8
            with:
              image-ref: ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.WEB_IMAGE_NAME }}:${{ steps.meta.outputs.version }}
              format: sarif
              output: trivy-web.sarif
              exit-code: '1'
              severity: HIGH,CRITICAL
              ignore-unfixed: true

          - name: Upload Web scan results to GitHub Security
            # github/codeql-action/upload-sarif — pinned SHA (v3.25.15)
            uses: github/codeql-action/upload-sarif@4fa2a7953630fd2f3fb380f21be14ede0169dd4f
            if: always()
            with:
              sarif_file: trivy-web.sarif

          - name: Build API image
            run: |
              docker build \
                -f src/PublicApi/Dockerfile \
                -t ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.API_IMAGE_NAME }}:${{ steps.meta.outputs.version }} \
                .

          - name: Scan API image for vulnerabilities
            uses: aquasecurity/trivy-action@6e7b7d1fd3e4fef0c5fa8cce1229c54b2c9bd0d8
            with:
              image-ref: ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.API_IMAGE_NAME }}:${{ steps.meta.outputs.version }}
              format: sarif
              output: trivy-api.sarif
              exit-code: '1'
              severity: HIGH,CRITICAL
              ignore-unfixed: true

          - name: Upload API scan results to GitHub Security
            uses: github/codeql-action/upload-sarif@4fa2a7953630fd2f3fb380f21be14ede0169dd4f
            if: always()
            with:
              sarif_file: trivy-api.sarif

          - name: Push Web image (SHA tag only — no :latest)
            run: |
              docker push ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.WEB_IMAGE_NAME }}:${{ steps.meta.outputs.version }}

          - name: Push API image (SHA tag only — no :latest)
            run: |
              docker push ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.API_IMAGE_NAME }}:${{ steps.meta.outputs.version }}

      # -------------------------------------------------------
      # Job 3: Deploy to Production
      # -------------------------------------------------------
      deploy:
        name: Deploy to Production
        runs-on: ubuntu-latest
        needs: build-and-push
        environment: production
        concurrency:
          group: production
          cancel-in-progress: false

        steps:
          - name: Checkout repository
            uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

          - name: Azure Login (OIDC)
            uses: azure/login@6c251865b4e6290e7b78be643ea2d005bc51f69a
            with:
              client-id: ${{ secrets.AZURE_CLIENT_ID }}
              tenant-id: ${{ secrets.AZURE_TENANT_ID }}
              subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

          - name: Deploy Web Container App
            # azure/container-apps-deploy-action — pinned SHA (v1.0.2)
            uses: azure/container-apps-deploy-action@b3e92af2088e32a445fad38498579a39fbf77ede
            with:
              resourceGroup: ${{ secrets.AZURE_RESOURCE_GROUP }}
              containerAppName: ${{ secrets.ACA_WEB_NAME }}
              imageToDeploy: ${{ secrets.ACR_LOGIN_SERVER }}/eshop/web:${{ needs.build-and-push.outputs.image-tag }}

          - name: Deploy API Container App
            uses: azure/container-apps-deploy-action@b3e92af2088e32a445fad38498579a39fbf77ede
            with:
              resourceGroup: ${{ secrets.AZURE_RESOURCE_GROUP }}
              containerAppName: ${{ secrets.ACA_API_NAME }}
              imageToDeploy: ${{ secrets.ACR_LOGIN_SERVER }}/eshop/publicapi:${{ needs.build-and-push.outputs.image-tag }}

          - name: Deploy BlazorAdmin to Static Web Apps
            # Azure/static-web-apps-deploy — pinned SHA (v1.4.0)
            uses: Azure/static-web-apps-deploy@1a947af9992250f3bc2e68ad0754c0b0c11566c9
            with:
              azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
              repo_token: ${{ secrets.GITHUB_TOKEN }}
              action: upload
              app_location: src/BlazorAdmin
              output_location: wwwroot

          - name: Verify deployment health
            run: |
              echo "Waiting 60 seconds for containers to stabilize..."
              sleep 60
              WEB_FQDN=$(az containerapp show \
                --name ${{ secrets.ACA_WEB_NAME }} \
                --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
                --query "properties.configuration.ingress.fqdn" -o tsv)
              echo "Web app FQDN: $WEB_FQDN"
              HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" "https://$WEB_FQDN/health/live")
              if [ "$HTTP_STATUS" != "200" ]; then
                echo "Health check failed with status: $HTTP_STATUS"
                exit 1
              fi
              echo "Deployment verified successfully."
  YAML
}
