<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>BlazorShared</RootNamespace>
    <AssemblyName>BlazorShared</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BlazorInputFile" />
    <PackageReference Include="FluentValidation" />
  </ItemGroup>

</Project>
